### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Yui-Ezic** [Xannosz/BetterMinecarts#1]
Idk when and why it really happens but after we crafted steam locomotive and launch it on rails server is crashed. It happens several times. I think it happens after a coliision with player/mob but not sure.

Minecraft: 1.20.1
Forge: 47.1.0
Mod version: 1.7.2 from curseforge 

Here is curseforge profile for our modpack: [Minecraft Sakurasou.zip](https://github.com/Xannosz/BetterMinecarts/files/12243371/Minecraft.Sakurasou.zip)

Here is crash reports:

[crash-2023-08-02_00.04.43-server.txt](https://github.com/Xannosz/BetterMinecarts/files/12243379/crash-2023-08-02_00.04.43-server.txt)
[crash-2023-08-02_00.15.18-server.txt](https://github.com/Xannosz/BetterMinecarts/files/12243380/crash-2023-08-02_00.15.18-server.txt)
[crash-2023-08-02_00.31.51-server.txt](https://github.com/Xannosz/BetterMinecarts/files/12243381/crash-2023-08-02_00.31.51-server.txt)

**Comment by Xannosz** [comment]
Hi, I try to reproduce the error. It caused maybe by an incompatibility between improvable skills and my mod. The fix will be released in this week, in the next patch (with other fixes and a new locomotive type).

**Comment by Xannosz** [comment]
Hi, I uploaded the new version to curseforge with the fix.

**Comment by Yui-Ezic** [comment]
Thank you, seems like it works

**Comment by Yui-Ezic** [comment]
Ok, it's crashed again
[crash-2023-08-16_01.47.15-server.txt](https://github.com/Xannosz/BetterMinecarts/files/12353592/crash-2023-08-16_01.47.15-server.txt)

**Comment by Xannosz** [comment]
Hi, I try to reproduce the bug, but I can not. So I try to fix it by the description:
https://github.com/Xannosz/BetterMinecarts/releases/tag/1.8.2
Please try it, maybe it solve the problem.

**Comment by Yui-Ezic** [comment]
We played several hours and try to test locomotive behavior and has no crashes
