### ISSUE TITLE
Better Minecarts on server.

### ISSUE THREAD

**Issue by Taknax** [Xannosz/BetterMinecarts#2]
Hi, i use your mazing mod on my server and this log i got in the console. Maybe you can fix.

<html>
<body>

[29Sep2023 21:18:16.164] [Worker-Main-1/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [betterminecarts:glowing_rail (from betterminecarts-1.20.1-1.8.1-47.1.0.jar)] as it is missing following references: betterminecarts:glowing_rail (from betterminecarts-1.20.1-1.8.1-47.1.0.jar)
--
370 | [29Sep2023 21:18:16.164] [Worker-Main-1/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#minecraft:rails (from minecolonies-1.20.1-1.1.171-RELEASE.jar)] as it is missing following references: #minecraft:rails (from minecolonies-1.20.1-1.1.171-RELEASE.jar)
371 | [29Sep2023 21:18:16.164] [Worker-Main-1/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#minecolonies:mechanic_product (from minecolonies-1.20.1-1.1.171-RELEASE.jar)] as it is missing following references: #minecolonies:mechanic_product (from minecolonies-1.20.1-1.1.171-RELEASE.jar)
372 | [29Sep2023 21:18:16.171] [Worker-Main-1/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#minecolonies:mechanic_product (from minecolonies-1.20.1-1.1.171-RELEASE.jar)] as it is missing following references: #minecolonies:mechanic_product (from minecolonies-1.20.1-1.1.171-RELEASE.jar)
373 | [29Sep2023 21:18:16.171] [Worker-Main-1/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [taxdl:dragon_heart (from TaxDragoneLegend+M.1.20.1+ForM.1.0.11.jar)] as it is missing following references: taxdl:dragon_heart (from TaxDragoneLegend+M.1.20.1+ForM.1.0.11.jar)
374 | [29Sep2023 21:18:16.171] [Worker-Main-1/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#minecolonies:mechanic_product (from minecolonies-1.20.1-1.1.171-RELEASE.jar)] as it is missing following references: #minecolonies:mechanic_product (from minecolonies-1.20.1-1.1.171-RELEASE.jar)

</body>
</html>

**Comment by Xannosz** [comment]
Hi, this message caused by a missing translation key from my language files. I didn't create this key because the glowing rail is a technical block , you shouldn't reach it as an item. Everything should works fine without this, but I will fix it in the next version.

**Comment by Taknax** [comment]
Totally ok when it is not effecting. TY.
